### PR TITLE
fix: increase default MCP server init timeout to 30s and surface env var in errors

### LINKED ISSUE #156: tiny change: increase the default init request timeout to 20 seconds
current default is 10 seconds - https://github.com/mcpjungle/MCPJungle/blob/main/cmd/start.go#L55

This is too less, especially when running mcpj inside docker (downloads for stdio servers can take time).

change default to 30.
make sure all documentation (readme) + cmd help messages + code comments reflect this

also, [in this error message](https://github.com/mcpjungle/MCPJungle/blob/main/internal/service/mcp/util.go#L269), tell the user about the `MCP_SERVER_INIT_REQ_TIMEOUT_SEC` env var so if they want, they can change the timeout.

### PR DESCRIPTION
**Pull request by tmchow**
## Summary

Bumps the default MCP server initialization timeout from 10 to 30 seconds and tells users about the `MCP_SERVER_INIT_REQ_TIMEOUT_SEC` env var when a timeout occurs.

## Why this matters

10 seconds is too tight for Docker environments where stdio servers need to download dependencies before starting. Users hit the timeout with no guidance on how to fix it. The error messages now point them to the env var directly.

## Changes

- `cmd/start.go`: Changed `McpServerInitRequestTimeoutSecondsDefault` from `10` to `30`. Updated the help text to reflect the new default.
- `internal/service/mcp/util.go`: Added `MCP_SERVER_INIT_REQ_TIMEOUT_SEC` env var hint to both the HTTP connection timeout error (line 210) and the stdio connection timeout error (line 294).

Test fixtures use hardcoded values independent of the default constant, so they remain unchanged.

Fixes #156

This contribution was developed with AI assistance (Claude Code).

### CODE REVIEW

File: internal/service/mcp/util.go [hunk 1]
```diff
@@ -207,7 +207,11 @@ func createHTTPMcpServerConn(ctx context.Context, s *model.McpServer, initReqTim
 	_, err = c.Initialize(initCtx, initRequest)
 	if err != nil {
 		if errors.Is(err, context.DeadlineExceeded) {
-			return nil, fmt.Errorf("initialization request to MCP server timed out after %d seconds", initReqTimeoutSec)
+			return nil, fmt.Errorf(
+				"initialization request to MCP server timed out after %d seconds."+
+					" Set the MCP_SERVER_INIT_REQ_TIMEOUT_SEC environment variable to increase this timeout",
```
Comment (duaraghav8) [inline internal/service/mcp/util.go]: Can you change this message to

"Set the MCP_SERVER_INIT_REQ_TIMEOUT_SEC environment variable for the mcpjungle server to increase this timeout"

It is important to tell the client that this env var can only be configuration on the mcpjungle server. This avoids confusion because they might try to set it for their cli when calling client commands, which isn't supported.

File: internal/service/mcp/util.go [hunk 2]
```diff
@@ -290,7 +294,8 @@ func runStdioServer(ctx context.Context, s *model.McpServer, initReqTimeoutSec i
 		if errors.Is(err, context.DeadlineExceeded) {
 			return nil, fmt.Errorf(
 				"initialization request to MCP server timed out after %d seconds,"+
-					" check mcpjungle server logs for any errors from this MCP server",
+					" check mcpjungle server logs for any errors from this MCP server."+
+					" Set the MCP_SERVER_INIT_REQ_TIMEOUT_SEC environment variable to increase this timeout",
```
Comment (duaraghav8) [inline internal/service/mcp/util.go]: Same comment as above

**Review by duaraghav8 — CHANGES_REQUESTED** [review]

**Comment by duaraghav8** [comment]
Thanks @tmchow This is mostly good, I requested a small change in the error messages.

**Comment by duaraghav8** [comment]
NVM, it was a small change so I pushed it
